# Generated by Django 2.2.7 on 2021-07-09 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='takenquiz',
            name='score',
        ),
    ]
