# Generated by Django 2.2.7 on 2021-07-09 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_create_initial_subjects'),
        ('classroom', '0002_auto_20210709_0504'),
    ]

    operations = [
    ]
